
services:

  node1:
    build: .
    container_name: node1

  node2:
    build: .
    container_name: node2

  node3:
    build: .
    container_name: node3

  node4:
    build: .
    container_name: node4

  node5:
    build: .
    container_name: node5

  client:
    build: .
    container_name: client
    command: python src/client.py